### ISSUE TITLE
[Feature Request]: Theme Button Add

### ISSUE THREAD

**Issue by alokchoudharyguliya** [mahaveergurjar/Chatbot#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add a theme switch button for the chat interface. Simply change of colour of the entire interface from dark to light and vice versa.Although it is simple but will give the application a good look and feel.

Attached UI:

![themeIssue](https://github.com/user-attachments/assets/f2338bd4-9d53-4880-92c9-520976b2906f)

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I want to work on this issue
- [x] I'm willing to provide further clarification or assistance if needed.

**Comment by mahaveergurjar** [comment]
yeah you can make light and dark theme button for this  app but i think button position are not good i think place at top not bottom look like this type 
![image](https://github.com/user-attachments/assets/320663dc-ab8c-4b02-9853-dd8ea64b0c8e)
![image](https://github.com/user-attachments/assets/435329af-0abb-40fc-997c-54f4baefba9c)
its looking more good
 make acc to your idea but not make like turn off on make like clickable toggle small button so look more good

**Comment by alokchoudharyguliya** [comment]
sure that will also work...i will do it accordingly

**Comment by mahaveergurjar** [comment]
okay

**Comment by alokchoudharyguliya** [comment]
![image](https://github.com/user-attachments/assets/421baea6-0268-4efc-ba2d-875025947455)
this way??

**Comment by mahaveergurjar** [comment]
Yeah this type place at right side

**Comment by mahaveergurjar** [comment]
issue resolved
