### ISSUE TITLE
[Feature Request]: UI menu for app position

### ISSUE THREAD

**Issue by mahaveergurjar** [mahaveergurjar/Chatbot#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 UI menu for app position  like three dot type in menu feature to position the app left, right, top, bottom of the screen you can see the feature is available in config.js file but i think if through menu possible then its more easy for your 

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by Abhinavexists** [comment]
i want to work on this issue.

**Comment by mahaveergurjar** [comment]
Okay
