### ISSUE TITLE
[Feature Request]: When maximize button pressed, whole page not extending

### ISSUE THREAD

**Issue by vigneshs-dev** [mahaveergurjar/Chatbot#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Normal ChatBot pic:
![Chatbot_Normal](https://github.com/user-attachments/assets/c72d2857-5dff-4537-8d16-5007aa589c22)
Maximized ChatBot pic:
![Chatbot_Maximized](https://github.com/user-attachments/assets/3af029ba-396d-4fa8-af22-96927e1202c1)

Edit screen not extending to full window.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mahaveergurjar** [comment]
Ok can you work on this issue ??

**Comment by vigneshs-dev** [comment]
> Ok can you work on this issue ??

I am new to javascript. But I went through the code. I think I can make it work. I will try my best @mahaveergurjar . Can you please attach hacktoberfest lable to this issue ?

**Comment by mahaveergurjar** [comment]
okay

**Comment by hemanthhhhhh** [comment]
Please assign this to me. Would love to contribute

**Comment by mahaveergurjar** [comment]
Its already assigned

**Comment by mahaveergurjar** [comment]
You can work on this @hemanthhhhhh 
![image](https://github.com/user-attachments/assets/b49bea49-de62-4e04-8d57-a253085ac74e)


Chat Application name and dark light toggle button are like same in chat not user differentiate in title bar and  chat area improve the ui of title add like box are shadow effect or add any thing that make ui more good

**Comment by mahaveergurjar** [comment]
make sure ui are responsive

**Comment by mahaveergurjar** [comment]
you can work on this @hemanthhhhhh  after the above issue fix of full screen so you can make ui responsive

**Comment by hemanthhhhhh** [comment]
Can you create this as a seperate issue and assign this to me with label as hacktoberfest @mahaveergurjar

**Comment by mahaveergurjar** [comment]
ok

**Comment by vigneshs-dev** [comment]
Hi @mahaveergurjar ,
I gone through the whole code and made some research. I found that all the Chat AI application don't extend their working area to the full length of the screen. So I made a little adjustment to the working area along with some modifications in input area. I will attach the screenshot for your reference.

![Chatbot_New](https://github.com/user-attachments/assets/dc67f602-2e0c-40be-8019-e0883419062e)

You can find the code in my [forked repository](https://github.com/vigneshs-dev/Chatbot.git). 
If you are ok with this design, I will make a Pull Request for merging.

**Comment by mahaveergurjar** [comment]
Its work on full screen also, don't give max-width in px give in %  like give max-width: 100%; then check ok because px are static not work for dynamic screen  always use %, em ,etc ok

**Comment by vigneshs-dev** [comment]
> Its work on full screen also, don't give max-width in px give in % like give max-width: 100%; then check ok because px are static not work for dynamic screen always use %, em ,etc ok

Sure. I changed the max-width in percentage format and I got the full page view. 
![Chatbot_FullScreen](https://github.com/user-attachments/assets/c9d860e6-abe5-41d5-a718-c66845cdbbd5)

Can I make a Pull Request now?
