### ISSUE TITLE
[Feature Request]: Fix title bar

### ISSUE THREAD

**Issue by mahaveergurjar** [mahaveergurjar/Chatbot#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Fix the ui of titlebar
![image](https://github.com/user-attachments/assets/ad1635dd-30be-432d-938d-ced9cce516ab)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by hemanthhhhhh** [comment]
Please assign this to me

**Comment by hemanthhhhhh** [comment]
and label it as hacktoberfest please

**Comment by alokchoudharyguliya** [comment]
I can contribute to this....label it as hactoberfest please

**Comment by mahaveergurjar** [comment]
@Pseudophoenix sorry the above person already say first

**Comment by mahaveergurjar** [comment]
@Pseudophoenix  I will make one for issue for ok in feature

**Comment by alokchoudharyguliya** [comment]
No worries sir

**Comment by OshadhaVimuB** [comment]
Can I fix this issue?

**Comment by mahaveergurjar** [comment]
@OshadhaVimuB make a good pr not like only change the margin and make pr like i said make good ui so Title bar look more good like because its good for you also to contribute good pr its  if anyone see you github profile then see you can contribute with good pr

**Comment by mahaveergurjar** [comment]
@OshadhaVimuB make something look like this type ok 
![image](https://github.com/user-attachments/assets/f4999930-125b-4818-9f48-207e3a39897b)

**Comment by OshadhaVimuB** [comment]
Thank you for your advice. This is my first PR. I'll try to do better next time

**Comment by alokchoudharyguliya** [comment]
Shall I fix This?

**Comment by mahaveergurjar** [comment]
Yeah you can try

**Comment by lightning-sagar** [comment]
hey can i work on this... and fi the styling...?

**Comment by alokchoudharyguliya** [comment]
@lightning-sagar try for something  else...like I have done this just tomorrow I will go for PR....try for something better...just a suggestion 😀

**Comment by lightning-sagar** [comment]
can i work on the light and dark mode... pls
