### ISSUE TITLE
[Documentation Update]: Add Theme Button Description

### ISSUE THREAD

**Issue by alokchoudharyguliya** [mahaveergurjar/Chatbot#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I would like to write in the readme file about the Theme Button and add some screenshots of the same

### Suggested Change

Two screenshots of the UI need to be added with some description about how the theme change button is working

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Abhinavexists** [comment]
i can do it.

**Comment by mahaveergurjar** [comment]
@Abhinavks1405 sorry first come first serve

**Comment by mahaveergurjar** [comment]
issue resolved #17
