### ISSUE TITLE
[Feature Request]: Dockerize Chatbot

### ISSUE THREAD

**Issue by vigneshs-dev** [mahaveergurjar/Chatbot#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hi @mahaveergurjar ,
I got an idea for Dockerizing the Chatbot as it lead for easy deployment on Cloud Services like AWS. If you are ok with this idea, I will start working on the implementation. 
Thankyou.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mahaveergurjar** [comment]
Okay you can make pr for this

**Comment by vigneshs-dev** [comment]
Hi @mahaveergurjar ,
I searched different websites for Dockerizing Electron. I think it will be difficult to achieve this. Can you suggest any idea or websites for this? As you are the one who created this wonderful ChatBot, your views really matter to me.
Thankyou.
