### ISSUE TITLE
[Feature Request]: Add Send icon

### ISSUE THREAD

**Issue by SaumyaSubham** [mahaveergurjar/Chatbot#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hii @mahaveergurjar 
Instead of using Send button, we can add there send icon button so that it'll be easy to send the messages.
Kindly assign me this under Hacktoberfest 2024

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I want to work on this issue
- [x] I'm willing to provide further clarification or assistance if needed.

**Comment by mahaveergurjar** [comment]
Okay you can add
