### ISSUE TITLE
[Feature Request]: Implement a New User Interface

### ISSUE THREAD

**Issue by OshadhaVimuB** [mahaveergurjar/Chatbot#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We need to design and implement a new user interface for the chatbot. I have already finished designing the user interface. Kindly assign me this under Hacktoberfest 2024

### Before:

![Screenshot 2024-10-05 214104](https://github.com/user-attachments/assets/6b84b9f5-4371-45c4-8b10-88ec0998b4af)

### After:

![Screenshot 2024-10-05 214306](https://github.com/user-attachments/assets/9299a6aa-9591-4ad0-bf44-7f69bb68b3f8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mahaveergurjar** [comment]
Its look good but why the outerline border its not look good so remove it and the sender message don't so in white color ok also make send button into icon like whatsapp or gemini app send button icon and make color ui like material ui with pastel color .

![image](https://github.com/user-attachments/assets/fd069457-3613-403f-9c27-2c97dc5833d7)


You can add get of color of user and copy button look like this type from this image

**Comment by OshadhaVimuB** [comment]
![image](https://github.com/user-attachments/assets/0f1d3395-bd00-44c1-afe9-40ab8c4943d1)


Is this design okay

**Comment by mahaveergurjar** [comment]
Yeah this design is good
