### ISSUE TITLE
[Feature Request]: Add color in code block 

### ISSUE THREAD

**Issue by mahaveergurjar** [mahaveergurjar/Chatbot#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add color in code block like variable and function show different color
![image](https://github.com/user-attachments/assets/62109b58-4881-4150-9c68-ea8920a540ba)

Show color like this type 
![image](https://github.com/user-attachments/assets/a6bd7b9a-5986-405d-95ed-0b840765c20f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by TarushGupta23** [comment]
i want to work here

**Comment by TarushGupta23** [comment]
finished
